it_company_task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("task_manager.urls", namespace="task_manager")),

    path("accounts/", include("django.contrib.auth.urls")),
]

task_manager/urls.py
from django.urls import path, include

from task_manager.views import (
    index,
    WorkerListView,
    TaskListView,
    TaskTypeView,
    WorkerCreateView,
    WorkerDetailView,
    WorkerPositionUpdateView,
    WorkerDeleteView,
    TaskDetailView,
    TaskUpdateView,
    TaskCreateView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    TaskDeleteView,
    TaskCompleteUpdateView,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView
)

urlpatterns = [
    path("", index, name="index"),

    path("worker/", WorkerListView.as_view(), name="worker-list"),
    path("worker/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("worker/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("worker/<int:pk>/update/", WorkerPositionUpdateView.as_view(), name="worker-update"),
    path("worker/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),

    path("task/", TaskListView.as_view(), name="task-list"),
    path("task/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/update/complete/", TaskCompleteUpdateView.as_view(), name="task-complete-toggle"),

    path("task-type/", TaskTypeView.as_view(), name="task-type-list"),
    path("task-type/create/", TaskTypeCreateView.as_view(), name="task-type-create"),
    path("task-type/<int:pk>/update/", TaskTypeUpdateView.as_view(), name="task-type-update"),
    path("task-type/<int:pk>/delete/", TaskTypeDeleteView.as_view(), name="task-type-delete"),

    path("position/", PositionListView.as_view(), name="position-list"),
    path("position/create/", PositionCreateView.as_view(), name="position-create"),
    path("position/<int:pk>/update/", PositionUpdateView.as_view(), name="position-update"),
    path("position/<int:pk>/delete/", PositionDeleteView.as_view(), name="position-delete"),
]


app_name = "task_manager"

templates/includes/footer.html
<footer class="footer pt-5 mt-5">
  <hr class="horizontal dark mb-5">
  <div class="container">
    <div class=" row">
      <div class="col-12">
        <div class="text-center">
          <h6 class="text-gradient text-primary font-weight-bolder">It Company Task Manager</h6>
          <p class="my-4 text-sm">
            It Company Task Manager by &copy; <a target="_blank" href="#" target="_blank">Mayor</a>
            - Coded by <a target="_blank" href="#" target="_blank">Mayor</a>.
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/includes/navigation.html
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid">
            <a class="navbar-brand font-weight-bolder ms-sm-3"
               href="{% url "task_manager:index" %}" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              Task Manager - Home
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a href="{% url "task_manager:worker-list" %}"><strong>Workers</strong></a>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a href="{% url "task_manager:task-list" %}"><strong>Tasks</strong></a>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a href="{% url "task_manager:task-type-list" %}"><strong>Task types</strong></a>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a href="{% url "task_manager:position-list" %}"><strong>Positions</strong></a>
                </li>
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2" href="{% url 'logout' %}">
                    <i class="fa fa-sign-out me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Logout">Logout</p>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/pagination.html
{% load query_transform %}


{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}

      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">{{ page_obj.previous_page_number }}</a>
      </li>

    {% endif %}

    <li class="page-item">
      <span class="page-link">{{ page_obj.number }}</span>
    </li>

    {% if page_obj.has_next %}

      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">{{ page_obj.next_page_number }}</a>
      </li>

    {% endif %}
  </ul>

{% endif %}

templates/includes/scripts.html
  <script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <h3>
      <strong>User:</strong> <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a>
    </h3>
    <li><strong><a href="{% url "logout" %}" class="btn btn-primary">Logout</a></strong></li>
    <br>
  {% else %}

    <li><strong><a href="{% url "login" %}" class="btn btn-primary">Login</a></strong></li>
    <br>

  {% endif %}

  <li class="list-group-item"><a href="{% url "task_manager:index" %}">Home</a></li>
  <li class="list-group-item"><a href="{% url "task_manager:worker-list" %}">All workers</a></li>
  <li class="list-group-item"><a href="{% url "task_manager:task-list" %}">All tasks</a></li>
  <li class="list-group-item"><a href="{% url "task_manager:task-type-list" %}">All task types</a></li>
  <li class="list-group-item"><a href="{% url "task_manager:position-list" %}">All positions</a></li>
</ul>

templates/includes/submit_btn.html
<input type="submit" value="Submit" class="btn btn-primary">