it_company_task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("task_manager.urls", namespace="task_manager")),

    path("accounts/", include("django.contrib.auth.urls")),
]

task_manager/urls.py
from django.urls import path, include

from task_manager.views import (
    index,
    WorkerListView,
    TaskListView,
    TaskTypeView,
    WorkerCreateView,
    WorkerDetailView,
    WorkerPositionUpdateView,
    WorkerDeleteView,
    TaskDetailView,
    TaskUpdateView,
    TaskCreateView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    TaskDeleteView,
    TaskCompleteUpdateView,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView
)

urlpatterns = [
    path("", index, name="index"),

    path("worker/", WorkerListView.as_view(), name="worker-list"),
    path("worker/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("worker/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("worker/<int:pk>/update/", WorkerPositionUpdateView.as_view(), name="worker-update"),
    path("worker/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),

    path("task/", TaskListView.as_view(), name="task-list"),
    path("task/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/update/complete/", TaskCompleteUpdateView.as_view(), name="task-complete-toggle"),

    path("task-type/", TaskTypeView.as_view(), name="task-type-list"),
    path("task-type/create/", TaskTypeCreateView.as_view(), name="task-type-create"),
    path("task-type/<int:pk>/update/", TaskTypeUpdateView.as_view(), name="task-type-update"),
    path("task-type/<int:pk>/delete/", TaskTypeDeleteView.as_view(), name="task-type-delete"),

    path("position/", PositionListView.as_view(), name="position-list"),
    path("position/create/", PositionCreateView.as_view(), name="position-create"),
    path("position/<int:pk>/update/", PositionUpdateView.as_view(), name="position-update"),
    path("position/<int:pk>/delete/", PositionDeleteView.as_view(), name="position-delete"),
]


app_name = "task_manager"

task_manager/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class TaskType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name


class Position(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(
        Position,
        on_delete=models.CASCADE,
        default=1
    )

    class Meta:
        verbose_name = "Worker"
        verbose_name_plural = "Workers"

    def __str__(self) -> str:
        if self.first_name and self.last_name:
            return f"{self.username} ({self.first_name} {self.last_name}) {self.position}"
        return f"{self.username} {self.position}"

    def get_absolute_url(self):
        return reverse("task_manager:worker-detail", kwargs={"pk": self.pk})


class Task(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateField(max_length=12)
    is_completed = models.BooleanField(default=False)
    created_on = models.DateField(auto_now_add=True)
    created_by = models.ForeignKey(Worker, on_delete=models.CASCADE)
    modified_on = models.DateTimeField(auto_now=True, blank=True, null=True)
    modified_by = models.ForeignKey(
        Worker,
        on_delete=models.DO_NOTHING,
        related_name="Project_modified_by",
        null=True,
        blank=True
    )

    PRIORITY_CHOICES = (
        ("HI", "High"),
        ("MED", "Medium"),
        ("LOW", "Low"),
    )

    priority = models.CharField(
        max_length=3,
        choices=PRIORITY_CHOICES,
        default="MED"
    )
    task_type = models.ForeignKey(
        TaskType,
        on_delete=models.CASCADE
    )

    assignees = models.ManyToManyField(Worker, related_name="tasks")

    def __str__(self) -> str:
        return f"{self.name}: {self.description}"

task_manager/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from task_manager.models import Worker, Task


class WorkerCreationForm(UserCreationForm):
    class Meta:
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "position",
        )


class WorkerSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        label="",
        required=False,
        widget=forms.TextInput(
            attrs={"placeholder": "Search by username..."}
        )
    )


class WorkerPositionUpdateForm(forms.ModelForm):
    class Meta:
        model = Worker
        fields = ["position"]


class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = [
            'name',
            'description',
            'task_type',
            'priority',
            'deadline',
            'assignees',
        ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'task_type': forms.Select(attrs={'class': 'form-control'}),
            'priority': forms.Select(attrs={'class': 'form-control'}),
            'assignees': forms.CheckboxSelectMultiple(),
            'deadline': forms.DateInput(
                format='%Y-%m-%d', attrs={
                    'class': 'form-control',
                    'placeholder': 'Select a date',
                    'type': 'date'
                }),

        }


class TaskSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            {"placeholder": "Search by name..."}
        )
    )

task_manager/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse, HttpRequest
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from task_manager.forms import (
    WorkerCreationForm,
    WorkerPositionUpdateForm,
    TaskForm,
    WorkerSearchForm,
    TaskSearchForm,
)
from task_manager.models import Task, TaskType, Worker, Position


@login_required
def index(request: HttpRequest) -> HttpResponse:

    num_tasks = Task.objects.count()
    in_proces_tasks = Task.objects.filter(is_completed=False).count()
    num_workers = Worker.objects.count()

    context = {
        "num_workers": num_workers,
        "num_tasks": num_tasks,
        "in_proces_tasks": in_proces_tasks,
    }

    return render(request, "task_manager/index.html", context=context)


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    paginate_by = 5
    template_name = "task_manager/worker_list.html"

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(WorkerListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = WorkerSearchForm(initial={
            "username": username
        })

        return context

    def get_queryset(self) -> QuerySet:
        queryset = Worker.objects.select_related("position")

        form = WorkerSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    template_name = "task_manager/worker_detail.html"


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Worker
    form_class = WorkerCreationForm


class WorkerPositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerPositionUpdateForm
    success_url = reverse_lazy("task_manager:worker-list")


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("task_manager:worker-list")


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    paginate_by = 5
    template_name = "task_manager/task_list.html"

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(TaskListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = TaskSearchForm(
            initial={
                "name": name
            }
        )

        return context

    def get_queryset(self) -> QuerySet:
        queryset = Task.objects.all().select_related("task_type")

        form = TaskSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return queryset


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task
    template_name = "task_manager/task_detail.html"
    queryset = Task.objects.prefetch_related("assignees__position")


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task_manager:task-list")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super(TaskCreateView, self).form_valid(form)


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task_manager:task-list")

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        super(TaskUpdateView, self).post(request, *args, **kwargs)
        task = Task.objects.get(pk=kwargs["pk"])
        task.modified_by = request.user
        task.save()
        return redirect(reverse_lazy("task_manager:task-list"))


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task_manager:task-list")
    template_name = "task_manager/task_confirm_delete.html"


class TaskCompleteUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    success_url = reverse_lazy("task_manager:task-list")

    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        status = Task.objects.get(pk=kwargs["pk"])
        status.is_completed = not status.is_completed
        status.save()
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


class TaskTypeView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    paginate_by = 5
    template_name = "task_manager/task_type_list.html"


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("task_manager:task-type-list")
    template_name = "task_manager/task_type_form.html"


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("task_manager:task-type-list")
    template_name = "task_manager/task_type_form.html"


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    success_url = reverse_lazy("task_manager:task-type-list")
    template_name = "task_manager/task_type_confirm_delete.html"


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    template_name = "task_manager/position_list.html"


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("task_manager:position-list")
    template_name = "task_manager/position_form.html"


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("task_manager:position-list")


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("task_manager:position-list")

templates/task_manager/index.html
{% extends "base-presentation.html" %}
{% load static %}


{% block title %} Task Manager {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block content %}

  <header class="header-2">
    <div class="page-header section-height-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/curved-images/curved.jpg')">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5 text-white">
                It Company Task Manager
            </h1>
            <p class="lead text-white mt-3">
              Manage your tasks easy here
            </p>
          </div>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40" />
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)" />
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)" />
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95" />
          </g>
        </svg>
      </div>
    </div>
  </header>
  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
          <div class="row">
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state1">{{ num_workers }}</span></h1>
                <h5 class="mt-3">Workers</h5>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"> <span id="state2">{{ num_tasks }}</span></h1>
                <h5 class="mt-3">Tasks</h5>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary" id="state3">{{ in_proces_tasks }}</h1>
                <h5 class="mt-3">In progres</h5>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>
  <script type="text/javascript">
    if (document.getElementById('state1')) {
      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
      if (!countUp.error) {
        countUp.start();
      } else {
        console.error(countUp.error);
      }
    }
    if (document.getElementById('state2')) {
      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
      if (!countUp1.error) {
        countUp1.start();
      } else {
        console.error(countUp1.error);
      }
    }
    if (document.getElementById('state3')) {
      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
      if (!countUp2.error) {
        countUp2.start();
      } else {
        console.error(countUp2.error);
      };
    }
  </script>

{% endblock javascripts %}

templates/task_manager/position_confirm_delete.html
{% extends "base-presentation.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <form action="" method="post" novalidate>
    {% csrf_token %}
    <h1>Are you sure you want to delete {{ position.name }} position?</h1>
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url "task_manager:position-list" %}" class="btn btn-primary">No</a>
  </form>
{% endblock %}

templates/task_manager/position_form.html
{% extends "base-presentation.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <div class="m-lg-2">
    <h2 class="mt-7 text-center">{{ object|yesno:"Update, Create" }} position: </h2>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      {% include "includes/submit_btn.html" %}
      <a href="{% url "task_manager:position-list" %}" class="btn btn-secondary">Return</a>
    </form>
  </div>
{% endblock %}

templates/task_manager/position_list.html
{% extends "base-presentation.html" %}


{% block content %}
  <div class="mt-4">
    <a href="{% url "task_manager:position-create" %}" class="btn btn-primary mt-2" style="float: right">Create</a>
    {% if position_list %}
      <table class="table">
        <tr>
          <th>ID</th>
          <th>Name</th>
        </tr>
        {% for position in position_list %}
          <tr>
            <td>{{ position.id }}</td>
            <td>{{ position.name }}</td>
            <td><a href="{% url "task_manager:position-update" pk=position.pk %}" class="btn btn-primary">Update</a></td>
            <td><a href="{% url "task_manager:position-delete" pk=position.pk %}" class="btn btn-danger">Delete</a></td>
          </tr>
        {% endfor %}
      </table>
  </div>
  {% else %}
    <h4>There is no positions</h4>
  {% endif %}
{% endblock %}

templates/task_manager/task_detail.html
{% extends "base-presentation.html" %}


{% block content %}
  <h3 class="d-lg-inline-block mt-7"><strong>{{ task.name }}</strong> :</h3>
  <table class="table">
    <tr>
      <th>Description</th>
      <th>Completed</th>
      <th>Deadline</th>
      <th>Created by</th>
      <th>Created on</th>
      <th>Modified by</th>
      <th>Modified on</th>
    </tr>
    <tr>
      <td>{{ task.description }}</td>
      <td>{{ task.is_completed }}</td>
      <td>{{ task.deadline }}</td>
      <td>{{ task.created_by.username }}</td>
      <td>{{ task.created_on }}</td>
      <td>{{ task.modified_by.username }}</td>
      <td>{{ task.modified_on }}</td>
    </tr>
  </table>
  <a href="{% url "task_manager:task-update" pk=task.id %}" class="btn btn-primary" style="float: right">
    Update
  </a>
  <div class="m-lg-4">
    <h3>{{ task.is_completed|yesno:"Worked, Working" }} on this task:</h3>
    {% for worker in task.assignees.all %}
      <h4><strong>Username: </strong>{{ worker.username }}</h4>
      <h4><strong>First name: </strong>{{ worker.first_name }}</h4>
      <h4><strong>Last name: </strong>{{ worker.last_name }}</h4>
      <h4><strong>Position: </strong>{{ worker.position }}</h4>
      <hr>
    {% endfor %}
    <a href="{% url "task_manager:task-list" %}" class="btn btn-secondary">Return</a>
  </div>
  <a href="{% url "task_manager:task-delete" pk=task.id %}" class="btn btn-danger" style="float: right">
    Delete
  </a>
  <a href="{% url "task_manager:task-complete-toggle" pk=task.id %}" class="btn btn-success" style="float: right">
    {{ task.is_completed|yesno:"Not complete, Complete" }}
  </a>
{% endblock %}

templates/task_manager/task_form.html
{% extends "base-presentation.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <div class="m-lg-2">
  <h1 class="mt-7 text-center">{{ object|yesno:"Update, Create" }} task :</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      {% if object %}
        <input type="submit" value="Submit" class="btn btn-primary">
      {% else %}
        {% include "includes/submit_btn.html" %}
      {% endif %}
      <a href="{% url "task_manager:task-list" %}" class="btn btn-secondary">
        Return
      </a>
    </form>
  </div>
{% endblock %}

templates/task_manager/task_list.html
{% extends "base-presentation.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <a href="{% url "task_manager:task-create" %}" class="btn btn-primary link-to-page" style="float: right">
    Create
  </a>
  {% if task_list %}
    <form action="" method="get" class="d-flex flex-row align-items-center flex-wrap mt-7">
      {{ search_form|crispy }}
      <input type="submit" value="Search" class="btn btn-secondary">
    </form>
    <table class="table align-items-center mb-0 mt-2">
      <tr>
        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Project</th>
        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Description</th>
        <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Priority</th>
        <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Completion</th>
        <th></th>
      </tr>
      {% for task in task_list %}
        <tr>
          <td>
            <div class="d-flex px-2">
              <div class="my-auto">
                <h6 class="mb-0 text-sm">{{ task.name }}</h6>
              </div>
            </div>
          </td>
          <td>
            <p class="text-sm font-weight-bold mb-0">{{ task.description }}</p>
          </td>
          <td>
            <p class="text-sm font-weight-bold mb-0">{{ task.priority }}</p>
          </td>
          <td class="align-middle text-center">
            <div class="d-flex align-items-center justify-content-center">
              <span class="me-2 text-xs font-weight-bold">{{ task.is_completed }}</span>
            </div>
          </td>
          <td class="align-middle">
              <a href="{% url "task_manager:task-detail" pk=task.id %}">
                More
              </a>
          </td>
        </tr>
      {% endfor %}
    </table>
    {% include "includes/pagination.html" %}
  {% else %}
    There are no tasks
  {% endif %}
{% endblock %}

templates/task_manager/task_type_confirm_delete.html
{% extends "base-presentation.html" %}


{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <div class="text-center">
      <h1 class="mt-7">
        Are you sure you want to delete {{ tasktype.name }} task type. <br>
        <strong>All tasks with this type will be deleted as well!!!</strong>
      </h1>
      <input type="submit" value="Delete" class="btn btn-danger">
      <a href="{% url "task_manager:task-type-list" %}" class="btn btn-success ">Return</a>
    </div>
  </form>
{% endblock %}

templates/task_manager/task_type_list.html
{% extends "base-presentation.html" %}


{% block content %}
  <div class="mt-4">
    <a href="{% url "task_manager:task-type-create" %}" class="btn btn-primary mt-2" style="float: right">
      Create
    </a>
    <table class="table">
      <tr>
        <td>ID</td>
        <td>Name</td>
      </tr>
      {% for task_type in tasktype_list %}
        <tr>
          <th>{{ task_type.id }}</th>
          <th>{{ task_type.name }}</th>
          <th><a href="{% url "task_manager:task-type-update" pk=task_type.id %}" class="btn btn-primary">Update</a></th>
          <th><a href="{% url "task_manager:task-type-delete" pk=task_type.id %}" class="btn btn-danger">Delete</a></th>
        </tr>
      {% endfor %}
    </table>
  </div>
  {% include "includes/pagination.html" %}
{% endblock %}

templates/task_manager/worker_detail.html
{% extends "base-presentation.html" %}


{% block content %}
  <div class="mt-7">
    <a href="{% url "task_manager:worker-delete" pk=worker.id %}" class="btn btn-danger" style="float: right">
      Delete
    </a>
    <a href="{% url "task_manager:worker-update" pk=worker.id %}" class="btn btn-primary" style="float: right">
      Update Position
    </a>
  </div>
  <table class="table align-items-center mt-7">
    <tr>
      <td><strong>Username: </strong>{{ worker.username }}</td>
      <td><strong>First name: </strong>{{ worker.first_name }}</td>
      <td><strong>Last name: </strong>{{ worker.last_name }}</td>
      <td><strong>Position: </strong>{{ worker.position }}</td>
      <td><strong>Admin: </strong>{{ worker.is_superuser }}</td>
    </tr>
  </table>
  <div class="text-center">
    <h3>All tasks:</h3>
    <hr>
    {% for task in worker.tasks.all %}

      <h4><strong>Task name: </strong><a href="{% url "task_manager:task-detail" pk=task.id %}">{{ task.name }}</a></h4>
      <h4><strong>Task description: </strong>{{ task.description }}</h4>
      <h4><strong>Task completed: </strong>{{ task.is_completed }}</h4><br>
      <hr>
    {% endfor %}
    <a href="{% url "task_manager:worker-list" %}" class="btn btn-secondary">
      Return
    </a>
  </div>
{% endblock %}

templates/task_manager/worker_list.html
{% extends "base-presentation.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <a href="{% url "task_manager:worker-create" %}" class="btn btn-primary link-to-page" style="float: right">Create</a>
  <form action="" method="get" class="d-flex flex-row align-items-center flex-wrap mt-7">
    {{ search_form|crispy }}
    <input type="submit" value="Search" class="btn btn-secondary">
  </form>
  {% if worker_list %}
    <table class="table align-items-center mb-0 ">
      <tr>
        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Worker</th>
        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Position</th>
        <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Employed</th>
        <th class="text-secondary opacity-7"></th>
      </tr>
      {% for worker in worker_list %}
        <tr>
          <td>
            <div class="d-flex px-2 py-1">
              <div class="d-flex flex-column justify-content-center">
                <h6 class="mb-0 text-sm">{{ worker.username }}</h6>
                {% if worker.email %}
                  <p class="text-xs text-secondary mb-0">{{ worker.email }}</p>
                {% else %}
                  <p class="text-xs text-secondary mb-0">email not provide</p>
                {% endif %}
              </div>
            </div>
          </td>
          <td>
            <p class="text-xs font-weight-bold mb-0">{{ worker.position }}</p>
          </td>
          <td class="align-middle text-center">
            <span class="text-secondary text-xs font-weight-bold">{{ worker.date_joined.date }}</span>
          </td>
          <td class="align-middle">
            <a href="{% url "task_manager:worker-detail" pk=worker.id %}" class="text-secondary font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Edit user">
              More
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>
    {% include "includes/pagination.html" %}
  {% else %}
    There are no workers
  {% endif %}
{% endblock %}